# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0fdebc2ed45435555584bcfd9825a46faa5056377cfda601345534f618346454a27e451f8535e3a7e67abee778647b34afac45fa9f3b0a588999e3f8722e903

test:
  secret_key_base: 0355b09d4aa0ef6a362899a674e19fdc0948510900940ef27f5e1cd39635124091fa82fe2ae423e92e7ffd0b4a87352ca775c51d9412cc2caac686d2a500d9a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
